#ifndef __UNCURL_CONST_H
#define __UNCURL_CONST_H

#define UNCURL_PORT    80
#define UNCURL_PORT_S  443

enum uncurl_scheme {
	UNCURL_NONE  = 0,
	UNCURL_HTTP  = 1,
	UNCURL_HTTPS = 2,
	UNCURL_WS    = 3,
	UNCURL_WSS   = 4,
};

enum uncurl_header_type {
	UNCURL_REQUEST  = 0,
	UNCURL_RESPONSE = 1,
};

enum ws_opcode {
	UNCURL_WSOP_CONTINUE = 0x0,
	UNCURL_WSOP_TEXT     = 0x1,
	UNCURL_WSOP_BINARY   = 0x2,
	UNCURL_WSOP_CLOSE    = 0x8,
	UNCURL_WSOP_PING     = 0x9,
	UNCURL_WSOP_PONG     = 0xa,
};

enum ws_status_code {
	UNCURL_CLOSE_NORMAL           = 1000,
	UNCURL_CLOSE_GOING_AWAY       = 1001,
	UNCURL_CLOSE_PROTOCOL         = 1002,
	UNCURL_CLOSE_DATA_TYPE        = 1003,
	UNCURL_CLOSE_NO_STATUS_CODE   = 1005,
	UNCURL_CLOSE_ABNORMAL_CLOSE   = 1006,
	UNCURL_CLOSE_DATA_CONSISTENCY = 1007,
	UNCURL_CLOSE_POLICY           = 1008,
	UNCURL_CLOSE_TOO_BIG          = 1009,
	UNCURL_CLOSE_EXTENSION        = 1010,
	UNCURL_CLOSE_UNEXPECTED       = 1011,
	UNCURL_CLOSE_TLS_HANDSHAKE    = 1015,
};

#endif
